### ISSUE TITLE
Cannot install note-it-js as described on a Raspberry Pi...

### ISSUE THREAD

**Issue by dl9sec** [inofix/note-it-js#18]
Hi,
unfortunately i can not install note-it-js as described on a Raspberry Pi with the latest Raspbian-lite.
I tried several ways, e.g. as user pi, with sudo, and as root with sudo su, but i got a lot of errors.

The first part, installing npm and babel-cli and babel-core seems to work:

% npm install babel-cli babel-core --save-dev
npm WARN optional dep failed, continuing fsevents@1.2.4
babel-cli@6.26.0 node_modules/babel-cli
├── slash@1.0.0
├── fs-readdir-recursive@1.1.0
├── path-is-absolute@1.0.1
├── convert-source-map@1.5.1
├── commander@2.16.0
├── v8flags@2.1.1 (user-home@1.1.1)
├── source-map@0.5.7
├── glob@7.1.2 (inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0, minimatch@3.0.4)
├── output-file-sync@1.1.2 (object-assign@4.1.1, graceful-fs@4.1.11, mkdirp@0.5.1)
├── chokidar@1.7.0 (inherits@2.0.3, async-each@1.0.1, glob-parent@2.0.0, is-glob@2.0.1, is-binary-path@1.0.1, readdirp@2.1.0, anymatch@1.3.2)
├── lodash@4.17.10
├── babel-register@6.26.0 (source-map-support@0.4.18, home-or-tmp@2.0.0, mkdirp@0.5.1, core-js@2.5.7)
├── babel-polyfill@6.26.0 (regenerator-runtime@0.10.5, core-js@2.5.7)
└── babel-runtime@6.26.0 (regenerator-runtime@0.11.1, core-js@2.5.7)

babel-core@6.26.3 node_modules/babel-core
├── slash@1.0.0
├── convert-source-map@1.5.1
├── path-is-absolute@1.0.1
├── babel-messages@6.23.0
├── private@0.1.8
├── babel-helpers@6.24.1
├── babel-template@6.26.0
├── json5@0.5.1
├── babylon@6.18.0
├── debug@2.6.9 (ms@2.0.0)
├── babel-types@6.26.0 (to-fast-properties@1.0.3, esutils@2.0.2)
├── minimatch@3.0.4 (brace-expansion@1.1.11)
├── source-map@0.5.7
├── babel-code-frame@6.26.0 (js-tokens@3.0.2, esutils@2.0.2, chalk@1.1.3)
├── babel-traverse@6.26.0 (globals@9.18.0, invariant@2.2.4)
├── babel-generator@6.26.1 (trim-right@1.0.1, jsesc@1.3.0, detect-indent@4.0.0)
├── lodash@4.17.10
├── babel-register@6.26.0 (source-map-support@0.4.18, home-or-tmp@2.0.0, mkdirp@0.5.1, core-js@2.5.7)
└── babel-runtime@6.26.0 (regenerator-runtime@0.11.1, core-js@2.5.7)

but when i try to install babel-preset-es2015 i got this:

% npm install babel-preset-es2015 --save-dev
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm ERR! tar.unpack untar error /root/.npm/core-js/2.5.7/package.tgz
npm ERR! tar.unpack untar error /root/.npm/core-js/2.5.7/package.tgz
npm ERR! tar.unpack untar error /root/.npm/lodash/4.17.10/package.tgz
npm ERR! tar.unpack untar error /root/.npm/core-js/2.5.7/package.tgz
npm ERR! tar.unpack untar error /root/.npm/core-js/2.5.7/package.tgz
npm ERR! tar.unpack untar error /root/.npm/lodash/4.17.10/package.tgz
npm ERR! tar.unpack untar error /root/.npm/core-js/2.5.7/package.tgz
npm ERR! tar.unpack untar error /root/.npm/lodash/4.17.10/package.tgz
npm ERR! tar.unpack untar error /root/.npm/babel-runtime/6.26.0/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/opt/note-it-js/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-parameters/node_modules/babel-runtime/node_modules/core-js'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  babel-preset-es2015@6.24.1 { [Error: ENOTEMPTY: directory not empty, rmdir '/opt/note-it-js/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-parameters/node_modules/babel-runtime/node_modules/core-js']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/opt/note-it-js/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-parameters/node_modules/babel-runtime/node_modules/core-js' }
npm ERR! nospc ENOSPC: no space left on device, mkdir '/opt/note-it-js/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-spread/node_modules/babel-runtime/node_modules/core-js'
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.

npm ERR! System Linux 4.14.52-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "babel-preset-es2015" "--save-dev"
npm ERR! cwd /opt/note-it-js
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! path /opt/note-it-js/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-spread/node_modules/babel-runtime/node_modules/core-js
npm ERR! syscall mkdir
npm ERR! fstream_path /opt/note-it-js/node_modules/babel-preset-es2015/node_modules/babel-plugin-transform-es2015-spread/node_modules/babel-runtime/node_modules/core-js
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code ENOSPC
npm ERR! errno -28
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/dir-writer.js:35:25
npm ERR! fstream_stack /usr/lib/nodejs/mkdirp/index.js:46:53
npm ERR! fstream_stack FSReqWrap.oncomplete (fs.js:82:15)
npm ERR! tar.unpack untar error /root/.npm/core-js/2.5.7/package.tgz
npm ERR! tar.unpack untar error /root/.npm/babel-runtime/6.26.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/core-js/2.5.7/package.tgz
npm ERR! tar.unpack untar error /root/.npm/lodash/4.17.10/package.tgz
npm ERR! tar.unpack untar error /root/.npm/core-js/2.5.7/package.tgz
npm ERR! tar.unpack untar error /root/.npm/core-js/2.5.7/package.tgz
npm ERR! tar.unpack untar error /root/.npm/lodash/4.17.10/package.tgz
npm ERR! tar.unpack untar error /root/.npm/core-js/2.5.7/package.tgz
npm ERR! tar.unpack untar error /root/.npm/lodash/4.17.10/package.tgz
npm ERR! tar.unpack untar error /root/.npm/lodash/4.17.10/package.tgz
npm ERR! tar.unpack untar error /root/.npm/core-js/2.5.7/package.tgz
npm ERR! tar.unpack untar error /root/.npm/lodash/4.17.10/package.tgz
npm ERR! tar.unpack untar error /root/.npm/core-js/2.5.7/package.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/note-it-js/npm-debug.log
npm ERR! not ok code 0

Any ideas whats going wrong and how it can be solved?

Thank you.

BTW:
Dateisystem    Größe Benutzt Verf. Verw% Eingehängt auf
/dev/root       3,6G    2,2G  1,3G   65% /

Regards, Thorsten

Update:
Installation in a working nodejs-environment also fails with:

c:\usr\node-it-js>npm run babel

> note-it@1.0.0 babel c:\usr\node-it-js
> babel --presets es2015 lib/noteit.es.js -o build/noteit.lib.js; babel --presets es2015 lib/noteit.board.es.js -o build/noteit.board.js

babel doesn't exist
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! note-it@1.0.0 babel: `babel --presets es2015 lib/noteit.es.js -o build/noteit.lib.js; babel --presets es2015 lib/noteit.board.es.js -o build/noteit.board.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the note-it@1.0.0 babel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2018-07-09T12_31_57_726Z-debug.log

**Comment by zwischenloesung** [comment]
Hi Thorsten,

the first error seems to come from the filesystem - 'no space left on device' or 'directory not empty' (as you have already noted - you provided the space consumption - but you might have missed the point, that some of the space might be freed up after the failure, e.g. temporary files beeing removed, so must control the free space during the installation. You might also want to check, if the target directory really is empty, maybe there is some junk from a previous installation laying around). The second error is due to babel not being installed in your second environement.

Hope that helps, good luck!
Yours,
Mic

BTW: You can also just copy the result of the build to your raspi... (note-it-js/build/noteit.board.js)

**Comment by zwischenloesung** [comment]
Hi Thorsten,

did you have the chance to test the issues?

Yours,
Mic

**Comment by zwischenloesung** [comment]
Hi Thorsten,

thank you for your answer. I will leave this ticket open until I have a "usable" / stable release. Then you (or others) will be able to directly download the final .js built without the hassle of translating it with babel.

All the best,
Mic

**Comment by dl9sec** [comment]
Hi Mic,

great stuff, thank you very much!

Regards, Thorsten

**Comment by zwischenloesung** [comment]
Hi Thorsten

If you want to give it another try. I have made a release now, with the ready built JavaScript added: https://github.com/inofix/note-it-js/releases

There is also a demo supporting all features implemented online now. I will add a very basic example too some day - maybe with just some yellow stickers and without the JSON part... Anyway, the demo is here:
https://inofix.github.io/note-it-js/example-sketchboard.html

I close this ticket now. Have fun.
Mic
