### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by zwischenloesung** [inofix/note-it-js#31]
Add CI integration..

**Comment by hugurp** [comment]
Some suggestions:

Tests:
- https://github.com/avajs/ava

Code linting:
- https://github.com/prettier/prettier — opinionated
- https://eslint.org — with config

CI:
- https://travis-ci.org

Do you see something missing?

**Comment by hugurp** [comment]
Hello @zwischenloesung, to activate https://travis-ci.org, you'll need to manually do an action as the repository owner.

Could you do the first 3 steps described here: https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci ?

I'm taking care of the rest (including the `.travis.yml` file).
