### ISSUE TITLE
Demo Site Broken

### ISSUE THREAD

**Issue by zwischenloesung** [inofix/note-it-js#37]
@hugurp I did not realize that your latest PR broke the demo-site at https://inofix.github.io/note-it-js/

How it works (or used to work.. :))
* the `index.html` must be in the root folder in order to get used by github.io (i.e. not in `/dist/`)
* the JavaScript files were working 'standalone', now I get a `SyntaxError: import declarations may only appear at top level of a module` at https://inofix.github.io/note-it-js/example-sketchboard.html

As I am new to all this JS-Magic, would you help me, getting this working again?

**Comment by hugurp** [comment]
Would this work?
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch

If `/docs/` is replaced by `/dist/`?

**Comment by zwischenloesung** [comment]
Nice solution with netlify! Just added the project.
