### ISSUE TITLE
License Change

### ISSUE THREAD

**Issue by zwischenloesung** [inofix/note-it-js#55]
Hi hugurp,

can you please confirm the change of the license for this project?
To make it "official":
GPLv3 -> double_license(GPLv3, MIT)

Thank you!

**Comment by hugurp** [comment]
Thanks for consulting with me :}
I don't have any ownership and lead of this project, and even if GPLv3 is great, this is not my decision to take!
Cheerss

**Comment by zwischenloesung** [comment]
You comitted code, so... :) - thank you for your statement!
